# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 tiangolo/uvicorn-gunicorn:python3.11

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ /app

# Define environment variable
ENV $(cat /app/.env | xargs)